### ISSUE TITLE
/src/common/header-vue-style-0.scss

### ISSUE THREAD

**Issue by blessbygod** [ccqgithub/fis3-parser-vue-component#10]
jade is ok,  3ks ccqgithub.

It's new issue:
file: header.vue
<style lang="scss">
@import '../assets/css/base.scss';
</style>

fis-conf.js : 
fis.match('*.scss', {
    rExt: '.css',
    useSprite: true,
    postprocessor: fis.plugin('autoprefixer'),
    parser: fis.plugin('node-sass')
});

error log: 
Can't find `/src/common/header-vue-style-0.scss`
    at Object.opts.importer (/usr/local/lib/node_modules/fis3-parser-node-sass/index.js:153:19)

**Comment by blessbygod** [comment]
应该是去找header-vue-style-0.css 文件的。

**Comment by ccqgithub** [comment]
我测试没有问题啊。。

**Comment by ccqgithub** [comment]
你把这个项目克隆下去，看看test里面的能跑不~

**Comment by ccqgithub** [comment]
已经可以了，v3.0.0，配置看文档

**Comment by blessbygod** [comment]
赞效率， 虽然昨天已经转为less了，
