### ISSUE TITLE
vue 单文件中style, lang=less 引用重复的资源，输出的css文件有冗余

### ISSUE THREAD

**Issue by blessbygod** [ccqgithub/fis3-parser-vue-component#11]
我一个header,  一个footer， 都import了 variable.less.

生成的都有重复的定义变量那部分的css。 

另外，产出顺序的问题。

vue组件生成的link的css，在html之前。

eg.

index.html
 
&lt;link rel="stylesheet" href="./index.less"&gt; 
&lt;ent-header>&lt;/ent-header&gt;
&lt;ent-footer&gt;&lt;/ent-footer&gt;

output: index.html  source code

    <link rel="stylesheet" type="text/css" href="/src/common/header-vue-style-0.css" />
    <link rel="stylesheet" type="text/css" href="/src/common/footer-vue-style-0.css" />
    <link rel="stylesheet" href="/src/index.css" />

**Comment by ccqgithub** [comment]
引用的组件样式本来就应该在前额，只有lessimport重复的问题，这是less的范畴，你两个文件import同一个，本来就会重复。
一般variable.less.应该只放变量和函数，如果非要两个文件import同一个，可看看less的`@import (onece) variable.less `, 不知道有没有记错

**Comment by blessbygod** [comment]
less 的 import once 已经合并为 import 了。
两个文件import同一个很正常的。 variable.less 如果在外部引用， .vue 会直接报变量未定义。

**Comment by ccqgithub** [comment]
这是less本身的问题，你两个less文件import另一个，一个less文件会知道另一个less文件是否import？
像你这种用法，应该使用@import (reference) variable.less;
