### ISSUE TITLE
 [ERROR] parser.0: parser.babel-6.x: Couldn't find preset "stage-3" relative to directory

### ISSUE THREAD

**Issue by huqiliang** [ccqgithub/fis3-parser-vue-component#13]
直接git clone这个仓库的报错 请问下是哪里出问题了么？
>win7
>fis3      3.3.29
>node   4.4.4
其他都是npm install

` [ERROR] parser.0: parser.babel-6.x: Couldn't find preset "stage-3" relative to
directory "F:/fis3-parser-vue-component/test/src/component" [F:/fis3-parser-vue-
component/test/src/component/a.vue] [F:/fis3-parser-vue-component/test/src/compo
nent/a.vue]`

**Comment by ccqgithub** [comment]
看信息是`babel-preset-stage-3`这个模块没有装成功
