### ISSUE TITLE
为什么不能支持vue单组件style的scoped属性呢？

### ISSUE THREAD

**Issue by blessbygod** [ccqgithub/fis3-parser-vue-component#14]
vuec 做了更细粒度的是挺好，但是还想要style级别的支持。

**Comment by ccqgithub** [comment]
scoped 要根据class去找对应的dom标签进行修改，不可控因素太多了，开发性价比不高，所以做了个简化版的~

**Comment by blessbygod** [comment]
其实用vue的这个功能就是开发及其简单，希望能给予支持。

**Comment by ccqgithub** [comment]
`scoped的是html5的一个属性，在style上加scoped之后，该样式只对当前元素和子元素有效。`

看了下[vue-loader](https://github.com/vuejs/vue-loader)的做法是通过postcss处理，将每一个classname对于的dom加一个hash属性。。这涉及到预处理语言，import，动态组件片段等各种可能出现bug的未知问题，要处理好工作量很大。。

所以我更倾向于自己手动控制scoped css的做法。。

如果不能满足你的需求很抱歉罗，目前我没有时间和精力去处理这个，我写这个插件也主要是为了方便工作，顺便分享出来。。。

本人能力有限，如果大家有好的idea，欢迎提交pr，或者fork重新发布一个插件也可以，期待fis3有更多更好的插件出来 🐱

**Comment by blessbygod** [comment]
我目前的理解是vue-loader既然做过了，不能集成到你写的这个fis3-parser里面吗？
