### ISSUE TITLE
cssScopedIdPrefix不唯一

### ISSUE THREAD

**Issue by biluochun** [ccqgithub/fis3-parser-vue-component#16]
比如：  
现有 `a.vue`(`__vuec__4`)  `b.vue`(`__vuec__5`)  
**重启**FIS3(这个功能每个人都需要,比如第二天使用FIS) 修改`a.vue`一开始ID是`__vuec__1`多修改几次后跟b重复了。  
其实就是--clear后ID值重新计算，这对文件版本控制不利。  
可能hash还是最优的。

**Comment by ccqgithub** [comment]
恩，好像是个问题

**Comment by ccqgithub** [comment]
做了优化，v4.0.0，参加readme
