### ISSUE TITLE
parse5.parseFragment(content)

### ISSUE THREAD

**Issue by atian25** [ccqgithub/fis3-parser-vue-component#2]
https://github.com/ccqgithub/fis3-parser-vue-component/blob/master/index.js#L23

这里应该修改为 `var fragment = parse5.parseFragment(content.toString()`

**Comment by ccqgithub** [comment]
不用，content本身就是string

**Comment by ccqgithub** [comment]
content

**Comment by atian25** [comment]
应该是之前我没加 isJsLike 导致 fis 没识别为 text file，所以传过去的是 buffer。
