### ISSUE TITLE
入口文件没有进行render函数编译

### ISSUE THREAD

**Issue by johnwaynerui** [ccqgithub/fis3-parser-vue-component#31]
发现新版本对于.vue文件里面的template进行了render函数的转换，并没有对入口文件处的`new Vue({
template: '<App/>'
})`的template字段进行render函数的替换，导致vue报错
![image](https://cloud.githubusercontent.com/assets/7790098/25118519/422eb98e-2449-11e7-962f-a2b77157a570.png)

**Comment by Treri** [comment]
fis3-parser-vue-component 只负责编译 .vue 单文件类型.

请问你的入口文件是怎么写的.

按我的理解的话, .vue文件中不会出现 `new Vue()`的调用吧

**Comment by johnwaynerui** [comment]
嗯嗯，.vue文件中不会出现new Vue调用,但是整个页面的入口main.js中要启动vue根实例就得写new Vue了，比如`new Vue({el: '#app', template: '<App/>'})` 这个App就是我的根组件。

**Comment by Treri** [comment]
@johnwaynerui 你可以看下 https://github.com/vuejs/vue-hackernews-2.0 中的写法.

或者像下面这样, 把App 放到一个单独的 .vue文件中, 然后在boot.js中引入

```js
import AppComponent from 'app.vue';

let options = Object.assign({
  el: '#container'
}, AppComponent);

new Vue(options);
```

**Comment by ccqgithub** [comment]
```
import AppComponent from 'app.vue';

let App = Vue.extend(AppComponent)

new App({}).$mount('#app')
```

**Comment by johnwaynerui** [comment]
@Treri @ccqgithub 多谢解答，知道怎么做了。
