### ISSUE TITLE
2.0以上编译vue-router的异步组件有问题

### ISSUE THREAD

**Issue by 303182519** [ccqgithub/fis3-parser-vue-component#32]
比如

`const foo = resolve => require(['components/foo.vue'], resolve)`

控制台报错

[Vue warn]: Failed to mount component: template or render function not defined. 
(found in <Anonymous> - use the "name" option for better debugging messages.)

**Comment by Treri** [comment]
你的 foo.vue是不是用了
```
export default {}
```
这种用法?

如果是的话, 请使用这种写法
```js
const foo = resolve => require(['components/foo.vue'], function(component){
  resolve(component.default);
})
```

**Comment by 303182519** [comment]
6666，解决了，假如不是这种写法呢

**Comment by Treri** [comment]
使用 es6 写法编译之后会变成
```js
exports['default'] = {}
```

但是如果你是使用 typescript 编译的话, 可以使用
```typescript
export = {}
```
这种写法. 经过ts编译之后就会变成
```js
module.exports = {}
```
