### ISSUE TITLE
运行的时候，老的代码报错了，怎么样做兼容

### ISSUE THREAD

**Issue by Baiang** [ccqgithub/fis3-parser-vue-component#33]
fis3 release 运行错误提示： [ERROR] parser.translate-es3ify: Parse Error: Line 5818: Invalid regular expression [F:/web/h5v3.0-demo/src/lib/vue2.0/vue.js] in [/js/house/house-list.js]

house-list.js代码：__inline('/lib/vue2.0/vue.js');

**Comment by Treri** [comment]
老的代码是指什么意思?

有没有能复现的例子可以看看是怎么回事

**Comment by Baiang** [comment]
找到原因了，translate-es3ify 编译错误 ，-。-！粗心大意
