### ISSUE TITLE
将css文件内联到js里面extractCSS: false, 导致cssSprite插件无效

### ISSUE THREAD

**Issue by 303182519** [ccqgithub/fis3-parser-vue-component#34]
background-image: url(/widget/header/new_nav_scan.png?__sprite);

**Comment by Treri** [comment]
请提供一个demo吧

**Comment by 303182519** [comment]
https://github.com/303182519/test-vue

**Comment by Treri** [comment]
@303182519 把 devDependecies 信息加上吧. 我都不知道我需要装哪些node_modules

**Comment by Treri** [comment]
你的 `.vue:scss` 里面并没有 `useSprite` 配置呀.

建议使用 fis3 inspect 看一下vue文件命中了哪条配置

**Comment by 303182519** [comment]
加上了，也不行

**Comment by 303182519** [comment]
https://github.com/fex-team/fis-spriter-csssprites

基于FIS的csssprites，对css文件,以及html文件css片段进行csssprites处理。

看了一下源码，fis3-parser-vue-component这个插件已经把css资源转化成js了，所以就无法处理了吧

**Comment by Treri** [comment]
![](https://raw.githubusercontent.com/fex-team/fis3/master/doc/docs/api/img/fis-compile-flow.png)

spriter阶段是发生在 packager 以后, 但是这时候 css已经被加入到 js 中了, 已经不是以css格式存在的了,  所以无法 spriter 了
