### ISSUE TITLE
2.5.2版本的vue 无法编译

### ISSUE THREAD

**Issue by biluochun** [ccqgithub/fis3-parser-vue-component#40]
Vue packages version mismatch:

- vue@2.5.2
- vue-template-compiler@2.4.4

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using vue-loader@>=10.0, simply update vue-template-compiler.
If you are using vue-loader@<10.0 or vueify, re-installing vue-loader/vueify should bump vue-template-compiler to the latest.

**Comment by ccqgithub** [comment]
试试 5.5.0
