### ISSUE TITLE
支持 scoped

### ISSUE THREAD

**Issue by atian25** [ccqgithub/fis3-parser-vue-component#6]
可以考虑下

**Comment by ccqgithub** [comment]
v2.1.0

**Comment by atian25** [comment]
https://vue-loader.vuejs.org/en/features/scoped-css.html

2.1.0 的实现貌似不符合 vue 的 spec

**Comment by ccqgithub** [comment]
这个没有按着vue-loader 的做法来，那样做太复杂了。。
